# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kokur&eacute;
author: Kokur&eacute; Fit
author_link: https://kokure.com
author_description: Kokur&eacute;
email: info@kokure.com
description: > # this means to ignore newlines until "baseurl:"
  Kokur&eacute;
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

liquid:
  error_mode: strict

# Sass
sass:
    style: :compressed
